# 使用nginx作为基础镜像
FROM nginx:alpine

# 将本地构建的静态文件复制到nginx容器
COPY ./dist /usr/share/nginx/html

# 复制nginx配置文件
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# 对外暴露80端口
EXPOSE 80

# 启动nginx
CMD ["nginx", "-g", "daemon off;"] 