version: '3.8'

services:
  # PostgreSQL数据库
  postgres:
    image: postgres:16-alpine
    container_name: excel-viewer-postgres
    restart: always
    environment:
      POSTGRES_DB: excel_viewer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # 后端API服务
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: excel-viewer-api
    restart: always
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: excel_viewer
      DB_USER: postgres
      DB_PASSWORD: postgres
      UPLOAD_DIR: uploads
    ports:
      - "3000:3000"
    volumes:
      - ./server/uploads:/app/uploads
    networks:
      - app-network

  # 前端服务
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: excel-viewer-client
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 