version: '3.8'

services:
  # PostgreSQL数据库
  postgres:
    image: postgres:16-alpine
    container_name: zhuohao-postgres
    restart: always
    environment:
      POSTGRES_DB: stock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # 后端API服务
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: zhuohao-api
    restart: always
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: stock
      DB_USER: postgres
      DB_PASSWORD: 123456
      UPLOAD_DIR: uploads
    ports:
      - "3000:3000"
    volumes:
      - ./server/uploads:/app/uploads
    networks:
      - app-network

  # 前端服务
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.local
    container_name: zhuohao-client
    restart: always
    depends_on:
      - api
    networks:
      - app-network

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: zhuohao-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 